server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://39.96.178.201:3306/practice_springboot?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



mybatis:
  # mapper.xml文件位置
  mapper-location: "classpath:mapper/*.xml"
  # dto实体位置
  type-aliases-package: com.cmlx.transaction.*.pojo.dto
